build:
  image: ubuntu:bionic
  script:
    - apt-get update && apt-get install -y curl software-properties-common gnupg1 unzip git apt-transport-https ca-certificates
    - curl -fsSL https://dl.winehq.org/wine-builds/winehq.key | apt-key add -
    - dpkg --add-architecture i386
    - apt-add-repository "deb https://dl.winehq.org/wine-builds/ubuntu/ bionic main"
    - apt-get update && apt-get install -y --install-recommends winehq-staging
    - ./build.shAfter a job finishes, if you visit the job’s specific page, there are three buttons. You can download the artifacts archive or browse its contents, whereas the Keep button appears only if you have set an expiry date to the artifacts in case you changed your mind and want to keep them.
  artifacts:
    paths:
      - dist/px.exe

